### ISSUE TITLE
Lastest Play store crashes with Zygisk Detach.

### ISSUE THREAD

**Issue by ravindu644** [j-hc/zygisk-detach#54]
**Android version and skin:** Android 12, One UI 4.1

**Screenshot of Play Store page of the app you are trying to detach:**

![Screenshot_20241010_184428_Settings](https://github.com/user-attachments/assets/b3377367-209a-4305-a2fc-8bdd7e054407)

**Screenshot of the helper CLI showing detached apps (from Option 2):**

![Screenshot_20241010_184507_zygisk-detach](https://github.com/user-attachments/assets/797d32d2-7d1a-4fab-82f1-cb183fe609fc)

Crash logs: 

```
FATAL EXCEPTION: main
Process: com.android.vending, PID: 31066
java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7614)
	at android.app.ActivityThread.access$1700(ActivityThread.java:315)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**

[log.txt](https://github.com/user-attachments/files/17328737/log.txt)

**Comment by j-hc** [comment]
you cant detach play store from play store

**Comment by ravindu644** [comment]
> you cant detach play store from play store

oh I'm messed up 😂😂

sorry 🥲
